#---
##################################
##################################
########## Auto Comment ##########
##################################
##################################
#name: Auto Comment
#on: [issues, pull_request]
#
#jobs:
#  run:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Auto Comment
#        uses: actions/checkout@v3
##        uses: wow-actions/auto-comment@v1.1.2
##        with:
##          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
##          issuesOpenedReactions: 'hooray, +1'
##          issuesOpenedComment: |
##            👋 @{{ author }}
##            Thank you for raising an issue. We will investigate into the matter and get back to you as soon as possible.
##            Please make sure you have given us as much context as possible.

---
#################################
#################################
## Super Linter GitHub Actions ##
#################################
#################################
name: Lint Code Base

#############################
# Start the job on all push #
#############################
on:
  push:
    branches-ignore: [master, main]
    # Remove the line above to run when pushing to master
  pull_request:
    branches: [master, main]

###############
# Set the Job #
###############
jobs:
  build:
    # Name the Job
    name: Lint Code Base
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper
          # list of changed files within `super-linter`
          fetch-depth: 0

      ################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
        uses: github/super-linter:slim-v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
