---
#################################
#################################
######### Auto Comment ##########
#################################
#################################
name: Auto Comment
on: [issues, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Auto Comment
        uses: actions/checkout@v3
#        uses: wow-actions/auto-comment@v1.1.2
#        with:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          issuesOpenedReactions: 'hooray, +1'
#          issuesOpenedComment: |
#            👋 @{{ author }}
#            Thank you for raising an issue. We will investigate into the matter and get back to you as soon as possible.
#            Please make sure you have given us as much context as possible.
